lang: en

theme: blue

title:
  en: SMEM
  es: SMEM
  ca: SMEM
  de: SMEM
  el: SMEM
  sr: SMEM
  sr-Latin: SMEM
  hr: SMEM
  fr: SMEM
logo:
  en: assets/img/smemlogo-1024x1024.png
apps:
  - apps/birds
  - apps/lilypond
  - apps/rabbitrint
  - apps/kaleidoskop
  - apps/barycenter2

# infoApp: apps/cindyjs/info
langMenuShow: true
langMenuItems:
  - en
  - de
  - es
  - ca
  - fr
  - sr
  - sr-Latin
  - hr
  - el
